FROM alpine:3.7
# RUN mkdir -p /go/src/app

RUN apk update && \
    apk upgrade

# Install all needed deps and compile the mesa llvmpipe driver from source.
RUN set -xe; \
    apk --update add --no-cache --virtual .runtime-deps xvfb llvm5-libs xdpyinfo; \
    apk add --no-cache --virtual .build-deps llvm-dev build-base zlib-dev glproto xorg-server-dev python-dev; \
    mkdir -p /var/tmp/build; \
    cd /var/tmp/build; \
    wget "https://mesa.freedesktop.org/archive/mesa-18.0.1.tar.gz"; \
    tar xfv mesa-18.0.1.tar.gz; \
    rm mesa-18.0.1.tar.gz; \
    cd mesa-18.0.1; \
    ./configure --enable-glx=gallium-xlib --with-gallium-drivers=swrast,swr --disable-dri --disable-gbm --disable-egl --enable-gallium-osmesa --prefix=/usr/local; \
    make; \
    make install; \
    cd .. ; \
    rm -rf mesa-18.0.1;

# RUN    apk add git sdl2-dev
RUN adduser -D -g '' appuser

WORKDIR /go/src/app

RUN go get -v github.com/veandco/go-sdl2/sdl
# RUN go get -v github.com/veandco/go-sdl2/img
# RUN go get -v github.com/veandco/go-sdl2/mix
# RUN go get -v github.com/veandco/go-sdl2/ttf

COPY ./src/ /go/src/app

USER appuser

#get dependancies

#build the binary
# RUN go run main.go
# RUN go build -o /go/bin/hello

# STEP 2 build a small image
# start from scratch
# FROM scratch
# Copy our static executable
# COPY --from=builder /go/bin/hello /go/bin/hello
# ENTRYPOINT ["/go/bin/hello"]
# ENTRYPOINT ["sh"]
ENTRYPOINT ["go", "run", "main.go"]